<?php
/* Generated by neoan3-cli */

namespace Neoan3\Model;

/**
 * Class {{name}}
 * @package Neoan3\Model
 */

class {{name}} extends IndexModel{
    /**
     * @param $id
     * @return mixed
     */
    function get(string $id)
    {
        return [];
    }
    /**
     * @param $condition
     * @return mixed
     */
    function find(array $condition)
    {
        return [];
    }
    /**
     * @param $id
     * @return mixed
     */
    function delete(string $id)
    {
        return [];
    }
}