<?php
/* Generated by neoan3-cli */

namespace Neoan3\Model;

/**
 * Class {{name}}
 * @package Neoan3\Model
 */

class {{name}}Model extends IndexModel{
    /**
     * @param $id
     * @return mixed
     */
    static function get(string $id)
    {
        return [];
    }
    /**
     * @param $condition
     * @return mixed
     */
    static function find(array $condition)
    {
        return [];
    }
    /**
     * @param $id
     * @return mixed
     */
    static function delete(string $id)
    {
        return [];
    }
}